apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-disk-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-disk-csi-driver-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: azure-disk-csi-driver-operator
    spec:
      containers:
      - args:
        - start
        env:
        - name: DRIVER_IMAGE
          # TODO: replace with OCP image once it's ready
          value: mcr.microsoft.com/k8s/csi/azuredisk-csi:latest
        - name: PROVISIONER_IMAGE
          value: quay.io/openshift/origin-csi-external-provisioner:latest
        - name: ATTACHER_IMAGE
          value: quay.io/openshift/origin-csi-external-attacher:latest
        - name: RESIZER_IMAGE
          value: quay.io/openshift/origin-csi-external-resizer:latest
        - name: SNAPSHOTTER_IMAGE
          value: quay.io/openshift/origin-csi-external-snapshotter:latest
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: quay.io/openshift/origin-csi-node-driver-registrar:latest
        - name: LIVENESS_PROBE_IMAGE
          value: quay.io/openshift/origin-csi-livenessprobe:latest
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
         # TODO: replace with OCP image once it's ready
        image: quay.io/bertinatto/azure-operator:v1
        imagePullPolicy: IfNotPresent
        name: azure-disk-csi-driver-operator
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
      priorityClassName: system-cluster-critical
      serviceAccountName: azure-disk-csi-driver-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
